import { Vendor, Testimonial } from './types'

// TODO: Replace with Supabase queries

export const mockVendors: Vendor[] = [
  {
    id: '1',
    name: 'Sharma Studio',
    category: 'Photographer',
    city: 'Mumbai',
    profileImage: '/vendors/photographer-1.jpg',
    coverImage: '/vendors/cover-1.jpg',
    about: 'With over 15 years of experience capturing magical wedding moments, Sharma Studio brings artistry and emotion to every frame. Our team specializes in candid photography, cinematic videos, and stunning pre-wedding shoots.',
    experience: '15+ years',
    minPrice: 50000,
    maxPrice: 300000,
    whatsapp: '+919876543210',
    instagram: 'sharmastudio',
    phone: '+919876543210',
    views: 2450,
    contactClicks: 156,
    favoritesCount: 89,
    isPremium: true,
    services: [
      { id: '1', name: 'Wedding Photography', description: 'Full day coverage with 2 photographers', price: 75000, priceType: 'starting' },
      { id: '2', name: 'Pre-wedding Shoot', description: '2 locations, 4 outfit changes', price: 35000, priceType: 'fixed' },
      { id: '3', name: 'Cinematic Video', description: 'Highlight reel + full ceremony coverage', price: 100000, priceType: 'starting' },
    ],
    gallery: ['/gallery/1-1.jpg', '/gallery/1-2.jpg', '/gallery/1-3.jpg', '/gallery/1-4.jpg'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Glamour by Priya',
    category: 'Makeup Artist',
    city: 'Delhi',
    profileImage: '/vendors/makeup-1.jpg',
    coverImage: '/vendors/cover-2.jpg',
    about: 'Celebrity makeup artist with expertise in bridal makeovers. Trained at Lakme Academy, specializing in airbrush makeup, HD techniques, and traditional bridal looks.',
    experience: '10+ years',
    minPrice: 25000,
    maxPrice: 150000,
    whatsapp: '+919876543211',
    instagram: 'glamourbypriya',
    phone: '+919876543211',
    views: 3200,
    contactClicks: 234,
    favoritesCount: 156,
    isPremium: true,
    services: [
      { id: '1', name: 'Bridal Makeup', description: 'Complete bridal look with hairstyling', price: 45000, priceType: 'starting' },
      { id: '2', name: 'Engagement Makeup', description: 'Party look with styling', price: 15000, priceType: 'fixed' },
      { id: '3', name: 'Family Package', description: 'Makeup for 5 family members', price: 35000, priceType: 'fixed' },
    ],
    gallery: ['/gallery/2-1.jpg', '/gallery/2-2.jpg', '/gallery/2-3.jpg', '/gallery/2-4.jpg'],
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Dream Weddings',
    category: 'Wedding Planner',
    city: 'Jaipur',
    profileImage: '/vendors/planner-1.jpg',
    coverImage: '/vendors/cover-3.jpg',
    about: 'We turn your wedding dreams into reality. From intimate ceremonies to grand celebrations, we handle everything - venue selection, vendor coordination, decor, and day-of management.',
    experience: '8+ years',
    minPrice: 200000,
    maxPrice: 2000000,
    whatsapp: '+919876543212',
    instagram: 'dreamweddings',
    phone: '+919876543212',
    views: 1890,
    contactClicks: 98,
    favoritesCount: 67,
    isPremium: true,
    services: [
      { id: '1', name: 'Full Planning', description: 'End-to-end wedding planning', price: 500000, priceType: 'starting' },
      { id: '2', name: 'Day Coordination', description: 'Day-of coordination and management', price: 100000, priceType: 'fixed' },
      { id: '3', name: 'Destination Wedding', description: 'Complete destination wedding planning', price: 1000000, priceType: 'starting' },
    ],
    gallery: ['/gallery/3-1.jpg', '/gallery/3-2.jpg', '/gallery/3-3.jpg', '/gallery/3-4.jpg'],
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Mehendi Magic',
    category: 'Mehendi Artist',
    city: 'Udaipur',
    profileImage: '/vendors/mehendi-1.jpg',
    coverImage: '/vendors/cover-4.jpg',
    about: 'Award-winning mehendi artist specializing in intricate bridal designs. We offer traditional Rajasthani, Arabic, and fusion patterns.',
    experience: '12+ years',
    minPrice: 8000,
    maxPrice: 50000,
    whatsapp: '+919876543213',
    instagram: 'mehendimagic',
    phone: '+919876543213',
    views: 1567,
    contactClicks: 123,
    favoritesCount: 78,
    isPremium: true,
    services: [
      { id: '1', name: 'Bridal Mehendi', description: 'Full hands and feet, intricate design', price: 25000, priceType: 'starting' },
      { id: '2', name: 'Guest Mehendi', description: 'Simple designs for guests', price: 500, priceType: 'starting' },
    ],
    gallery: ['/gallery/4-1.jpg', '/gallery/4-2.jpg', '/gallery/4-3.jpg', '/gallery/4-4.jpg'],
    createdAt: '2024-02-10',
  },
  {
    id: '5',
    name: 'Royal Decor',
    category: 'Decorator',
    city: 'Bangalore',
    profileImage: '/vendors/decor-1.jpg',
    coverImage: '/vendors/cover-5.jpg',
    about: 'Transform your venue into a magical wonderland. We specialize in floral arrangements, lighting, mandap decoration, and themed setups.',
    experience: '7+ years',
    minPrice: 100000,
    maxPrice: 1000000,
    whatsapp: '+919876543214',
    instagram: 'royaldecor',
    phone: '+919876543214',
    views: 2100,
    contactClicks: 167,
    favoritesCount: 92,
    isPremium: true,
    services: [
      { id: '1', name: 'Complete Venue Decor', description: 'Full venue transformation', price: 300000, priceType: 'starting' },
      { id: '2', name: 'Mandap Decoration', description: 'Traditional or contemporary mandap', price: 150000, priceType: 'starting' },
      { id: '3', name: 'Floral Arrangements', description: 'Fresh flower centerpieces and decor', price: 50000, priceType: 'starting' },
    ],
    gallery: ['/gallery/5-1.jpg', '/gallery/5-2.jpg', '/gallery/5-3.jpg', '/gallery/5-4.jpg'],
    createdAt: '2024-01-25',
  },
  {
    id: '6',
    name: 'DJ Rhythms',
    category: 'DJ',
    city: 'Pune',
    profileImage: '/vendors/dj-1.jpg',
    coverImage: '/vendors/cover-6.jpg',
    about: 'Get the party started with our high-energy DJ services. We bring the best sound systems, lighting, and music to make your sangeet unforgettable.',
    experience: '6+ years',
    minPrice: 30000,
    maxPrice: 150000,
    whatsapp: '+919876543215',
    instagram: 'djrhythms',
    phone: '+919876543215',
    views: 980,
    contactClicks: 67,
    favoritesCount: 45,
    isPremium: false,
    services: [
      { id: '1', name: 'Sangeet Night', description: 'Full night with sound and lights', price: 50000, priceType: 'fixed' },
      { id: '2', name: 'Cocktail Party', description: 'Premium DJ setup for 4 hours', price: 35000, priceType: 'fixed' },
    ],
    gallery: ['/gallery/6-1.jpg', '/gallery/6-2.jpg', '/gallery/6-3.jpg', '/gallery/6-4.jpg'],
    createdAt: '2024-02-15',
  },
  {
    id: '7',
    name: 'Annapurna Caterers',
    category: 'Caterer',
    city: 'Bhopal',
    profileImage: '/vendors/caterer-1.jpg',
    coverImage: '/vendors/cover-7.jpg',
    about: 'Serving delicious multi-cuisine wedding feasts for over two decades. From traditional thalis to live counters, we cater to all tastes.',
    experience: '20+ years',
    minPrice: 500,
    maxPrice: 2500,
    whatsapp: '+919876543216',
    instagram: 'annapurnacaterers',
    phone: '+919876543216',
    views: 1450,
    contactClicks: 89,
    favoritesCount: 56,
    isPremium: false,
    services: [
      { id: '1', name: 'Vegetarian Menu', description: 'Per plate with 15+ items', price: 800, priceType: 'starting' },
      { id: '2', name: 'Non-Veg Menu', description: 'Per plate with 18+ items', price: 1200, priceType: 'starting' },
      { id: '3', name: 'Live Counters', description: 'Chaat, pasta, dosa stations', price: 15000, priceType: 'per-day' },
    ],
    gallery: ['/gallery/7-1.jpg', '/gallery/7-2.jpg', '/gallery/7-3.jpg', '/gallery/7-4.jpg'],
    createdAt: '2024-01-10',
  },
  {
    id: '8',
    name: 'Pre-wed Films',
    category: 'Pre-wedding Shoot',
    city: 'Goa',
    profileImage: '/vendors/prewed-1.jpg',
    coverImage: '/vendors/cover-8.jpg',
    about: 'Capture your love story against stunning backdrops. We specialize in cinematic pre-wedding films and photography at exotic locations.',
    experience: '5+ years',
    minPrice: 40000,
    maxPrice: 200000,
    whatsapp: '+919876543217',
    instagram: 'prewedfilms',
    phone: '+919876543217',
    views: 2890,
    contactClicks: 201,
    favoritesCount: 134,
    isPremium: true,
    services: [
      { id: '1', name: 'Beach Shoot', description: 'Full day at Goa beaches', price: 60000, priceType: 'fixed' },
      { id: '2', name: 'Cinematic Film', description: '3-minute highlight video', price: 80000, priceType: 'fixed' },
    ],
    gallery: ['/gallery/8-1.jpg', '/gallery/8-2.jpg', '/gallery/8-3.jpg', '/gallery/8-4.jpg'],
    createdAt: '2024-02-05',
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ananya & Rahul',
    location: 'Mumbai',
    image: '/testimonials/couple-1.jpg',
    text: 'BandhanHub made our wedding planning so easy! We found the perfect photographer and decorator through the platform. Highly recommended!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Meera & Vikram',
    location: 'Delhi',
    image: '/testimonials/couple-2.jpg',
    text: 'The vendor quality on BandhanHub is exceptional. Our makeup artist was amazing and the whole booking process was seamless.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Kavya & Arjun',
    location: 'Bangalore',
    image: '/testimonials/couple-3.jpg',
    text: 'We were skeptical at first, but BandhanHub connected us with vendors who truly understood our vision. Our wedding was magical!',
    rating: 5,
  },
]

export function getVendorById(id: string): Vendor | undefined {
  return mockVendors.find(v => v.id === id)
}

export function getFeaturedVendors(): Vendor[] {
  return mockVendors.filter(v => v.isPremium)
}

export function getAllVendors(): Vendor[] {
  return mockVendors
}

export function filterVendors(category?: string, city?: string, minBudget?: number, maxBudget?: number): Vendor[] {
  return mockVendors.filter(vendor => {
    if (category && vendor.category !== category) return false
    if (city && !vendor.city.toLowerCase().includes(city.toLowerCase())) return false
    if (minBudget && vendor.maxPrice < minBudget) return false
    if (maxBudget && vendor.minPrice > maxBudget) return false
    return true
  })
}
